title: Nexus
description: Nexus | network of extensible sources
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nexus-dock.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  ".fridge/", ".vscode/", "LICENSE", "README.md"]
collections:
  docs:
    output: true
  demo:
    output: true
  pages:
    output: true
  root:
    output: true
defaults:
  -
    scope:
      path: "_root"
    values:
      no_footer: true
      layout: "page"
      stylesheet: "/assets/css/NxPages.css"
  -
    scope:
      path: "_pages"
    values:
      layout: "page"
      stylesheet: "/assets/css/NxPages.css"
  -
    scope:
      path: "_docs"
    values:
      layout: "page"
      stylesheet: "/assets/css/NxPages.css"
  -
    scope:
      path: "_demo"
    values:
      layout: "demo"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all