title: Nexus
description: Nexus | network of extensible sources
defaults:
  -
    scope:
      path: "docs"
    values:
      layout: "default"
collections:
  docs:
    permalink: "/:path/"
    output: true
  demo:
    permalink: "/:collection/:path/"
    output: true