title: Nexus
description: Nexus | network of extensible sources
collections:
  docs:
    layout: base
    permalink: "/:path/"
    output: true
  demo:
    layout: base
    permalink: "/:collection/:path/"
    output: true